DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
DEBUG:h5py._conv:Creating converter from 3 to 5
ERROR:root:Exception occurred
Traceback (most recent call last):
  File "C:\xampp\htdocs\Project_website\python_codes\emotion_recognition.py", line 41, in <module>
    emotion_prediction = emotion_classifier.predict(roi_gray)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\002\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
